
 if(MSVC)
  set(boost_lib_args
   -DENABLE_SHARED:BOOL=OFF
   -DENABLE_STATIC:BOOL=ON)
else()
 set(boost_lib_args
   -DENABLE_SHARED:BOOL=ON
   -DENABLE_STATIC:BOOL=OFF)
endif()

#Boost bjam version
add_external_project(boost
  LIST_SEPARATOR ::
  CMAKE_ARGS
   ${boost_lib_args}
   -DBUILD_PROJECTS:STRING=filesystem::system::thread
   -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
   -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=<INSTALL_DIR>/lib
   -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=<INSTALL_DIR>/lib
   -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=<INSTALL_DIR>/lib
   -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=<INSTALL_DIR>/lib
   -DBUILD_EXAMPLES:BOOL=OFF
   -DBUILD_TESTING:BOOL=OFF
   -DBUILD_VERSIONED:BOOL=OFF
   -DINSTALL_VERSIONED:BOOL=OFF
   -DWINMANGLE_LIBNAMES:BOOL=OFF
   -DWITH_MPI:BOOL=OFF
   -DWITH_PYTHON:BOOL=OFF
   -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
   )